from PyQt5.QtCore import Qt, QRect, QSize
from PyQt5.QtGui import QIcon, QFont, QPainter, QBrush, QColor, QPen
from PyQt5.QtWidgets import QPushButton, QHBoxLayout
import qtawesome as qta


class MainWindowStyle:
    def __init__(self, ui):
        self.ui = ui
        # Side panel
        self.ui.staking_button.setVisible(False)
        self.ui.staking_button = ToggleSwitch(self.ui.miningstatus_frame)  # Add custom Toggle button
        self.ui.mininggrid_Layout.addWidget(self.ui.staking_button, 1, 1, 1, 1)
        self.ui.mining_button.setVisible(False)
        self.ui.mining_button = ToggleSwitch(self.ui.miningstatus_frame)  # Add custom Toggle button
        self.ui.walletsummary_hide_button.setIcon(qta.icon('ei.eye-close', color='#cc2900'))
        # Stats
        self.ui.mininggrid_Layout.addWidget(self.ui.mining_button, 3, 1, 1, 1)
        self.ui.stats_pie_frame.setContentsMargins(0, 0, 0, 0)
        self.ui.stats_layout = QHBoxLayout(self.ui.stats_pie_frame)
        self.ui.stats_layout.setContentsMargins(0, 0, 0, 0)

    def set_icon_color(self, color):
        # Login remote tab
        self.ui.serveradd_button.setIcon(qta.icon('fa.plus', color=color))
        self.ui.serveradd_button.setIconSize(QSize(24, 24))
        self.ui.serveredit_button.setIcon(qta.icon('ei.edit', color=color))
        self.ui.serveredit_button.setIconSize(QSize(24, 24))
        self.ui.connect_button.setIcon(qta.icon('mdi.lan-connect', color=color))
        self.ui.connect_button.setIconSize(QSize(24, 24))
        self.ui.home_button.setIcon(qta.icon('fa.home', color=color))
        self.ui.home_button.setIconSize(QSize(24, 24))
        self.ui.edit_serversave_button.setIcon(qta.icon('fa.save', color=color))
        self.ui.edit_serversave_button.setIconSize(QSize(24, 24))
        self.ui.add_serversave_button.setIcon(qta.icon('fa.save', color=color))
        self.ui.add_serversave_button.setIconSize(QSize(24, 24))
        self.ui.servercancel_button.setIcon(qta.icon('mdi.cancel', color=color))
        self.ui.servercancel_button.setIconSize(QSize(24, 24))
        self.ui.serverdelete_button.setIcon(qta.icon('mdi.delete-forever', color=color))
        self.ui.serverdelete_button.setIconSize(QSize(24, 24))
        # Chain page
        self.ui.download_blocks_button.setIcon(qta.icon('mdi.cloud-download-outline', color=color))
        self.ui.download_blocks_button.setIconSize(QSize(24, 24))
        self.ui.refresh_walletaddresses_button.setIcon(qta.icon('mdi.refresh', color=color))
        self.ui.refresh_walletaddresses_button.setIconSize(QSize(24, 24))
        self.ui.check_fork_button.setIcon(qta.icon('mdi.directions-fork', color=color))
        self.ui.check_fork_button.setIconSize(QSize(24, 24))
        self.ui.addaddress_page_button.setIcon(qta.icon('fa.plus', color=color))
        self.ui.addaddress_page_button.setIconSize(QSize(24, 24))
        self.ui.address_seed_button.setIcon(qta.icon('mdi.seed-outline', color=color))
        self.ui.address_seed_button.setIconSize(QSize(24, 24))
        self.ui.newaddress_button.setIcon(qta.icon('mdi.credit-card-plus-outline', color=color))
        self.ui.newaddress_button.setIconSize(QSize(24, 24))
        self.ui.addresspage_back_button.setIcon(qta.icon('mdi.step-backward', color=color))
        self.ui.addresspage_back_button.setIconSize(QSize(24, 24))
        self.ui.privatekeypage_back_button.setIcon(qta.icon('mdi.step-backward', color=color))
        self.ui.privatekeypage_back_button.setIconSize(QSize(24, 24))
        self.ui.importprivkey_button.setIcon(qta.icon('mdi.application-import', color=color))
        self.ui.importprivkey_button.setIconSize(QSize(24, 24))
        self.ui.privkey_page_button.setIcon(qta.icon('mdi.incognito', color=color))
        self.ui.privkey_page_button.setIconSize(QSize(24, 24))
        self.ui.debug_button.setIcon(qta.icon('fa.bug', color=color))
        self.ui.debug_button.setIconSize(QSize(16, 16))
        # menubar
        self.ui.actionQuit.setIcon(qta.icon('fa.close', color=color))
        self.ui.actionLogout.setIcon(qta.icon('mdi.logout', color=color))
        self.ui.menuDebug.setIcon(qta.icon('fa.bug', color=color))
        self.ui.actionAbout.setIcon(qta.icon('fa.info', color=color))
        self.ui.actionPreferences.setIcon(qta.icon('ph.gear-six', color=color))
        # self.ui.actionLanguage_Selection.setIcon(qta.icon('ei.flag', color=color))
        # self.ui.actionAppearances.setIcon(qta.icon('fa.paint-brush', color=color))
        self.ui.actionSee_Log_File.setIcon(qta.icon('mdi.file-document-outline', color=color))
        self.ui.actionSee_chain_Log_File.setIcon(qta.icon('mdi.file-document-outline', color=color))
        self.ui.actionCheck_for_Update.setIcon(qta.icon('mdi.open-in-app', color=color))
        # mcl tab
        self.ui.mcl_tab.setTabIcon(0, qta.icon('fa.chain', color=color))
        self.ui.mcl_tab.setTabIcon(1, qta.icon('fa5s.wallet', color=color))
        self.ui.mcl_tab.setTabIcon(2, qta.icon('fa5s.coins', color=color))
        self.ui.mcl_tab.setTabIcon(3, qta.icon('fa5b.hornbill', color=color))
        self.ui.mcl_tab.setTabIcon(4, qta.icon('fa5.address-card', color=color))
        self.ui.mcl_tab.setTabIcon(5, qta.icon("mdi.chart-areaspline", color=color))
        self.ui.mcl_tab.setTabIcon(6, qta.icon("mdi.bulletin-board", color=color))
        self.ui.mcl_tab.setIconSize(QSize(28, 28))
        # Side panel
        self.ui.getinfo_refresh_button.setIcon(qta.icon('ei.refresh', color=color))
        self.ui.getinfo_refresh_button.setIconSize(QSize(24, 24))
        # self.ui.walletsummary_hide_button.setIconSize(QSize(24, 24))
        self.ui.copyaddress_button.setIcon(qta.icon('fa5.copy', color=color))
        self.ui.copyaddress_button.setIconSize(QSize(24, 24))
        self.ui.copypubkey_button.setIcon(qta.icon('mdi.key-change', color=color))
        self.ui.copypubkey_button.setIconSize(QSize(24, 24))
        self.ui.fontsize_minus_button.setIcon(qta.icon('mdi.format-font-size-decrease', color=color))
        self.ui.fontsize_minus_button.setIconSize(QSize(24, 24))
        self.ui.fontsize_plus_button.setIcon(qta.icon('mdi.format-font-size-increase', color=color))
        self.ui.fontsize_plus_button.setIconSize(QSize(24, 24))
        self.ui.youtube_button.setIcon(qta.icon('fa5b.youtube', color=color))
        self.ui.youtube_button.setIconSize(QSize(18, 18))
        self.ui.discord_button.setIcon(qta.icon('fa5b.discord', color=color))
        self.ui.discord_button.setIconSize(QSize(18, 18))
        self.ui.website_button.setIcon(qta.icon('mdi.web', color=color))
        self.ui.website_button.setIconSize(QSize(18, 18))
        # Wallet page button icons
        self.ui.lock_button.setIcon(QIcon(qta.icon('fa5s.lock', color=color)))
        self.ui.lock_button.setIconSize(QSize(32, 32))
        self.ui.unlock_button.setIcon(QIcon(qta.icon('fa5s.unlock-alt', color=color)))
        self.ui.unlock_button.setIconSize(QSize(32, 32))
        self.ui.addressamount_refresh_button.setIcon(qta.icon('mdi.refresh', color=color))
        self.ui.addressamount_refresh_button.setIconSize(QSize(24, 24))
        self.ui.refresh_loopinfo_button.setIcon(qta.icon('mdi.refresh', color=color))
        self.ui.refresh_loopinfo_button.setIconSize(QSize(24, 24))
        # Coin Send-Receive page
        self.ui.coinsend_button.setIcon(qta.icon('mdi.database-export', color=color))
        self.ui.coinsend_button.setIconSize(QSize(24, 24))
        self.ui.transaction_search_button.setIcon(qta.icon('fa.search', color=color))
        self.ui.transaction_search_button.setIconSize(QSize(24, 24))
        self.ui.qrcode_button.setIcon(qta.icon('mdi.qrcode', color=color))
        self.ui.qrcode_button.setIconSize(QSize(48, 48))
        # Credit loops page
        self.ui.creditloop_tabWidget.setTabIcon(0, qta.icon('mdi.arrow-down-circle-outline', color=color))
        self.ui.creditloop_tabWidget.setTabIcon(1, qta.icon('mdi.link-variant-plus', color=color))
        self.ui.creditloop_tabWidget.setTabIcon(2, qta.icon('mdi.vector-circle', color=color))
        self.ui.creditloop_tabWidget.setTabIcon(3, qta.icon('mdi.database-search', color=color))
        self.ui.creditloop_tabWidget.setIconSize(QSize(24, 24))
        # Stats page
        self.ui.stats_tabWidget.setTabIcon(0, qta.icon('fa.pie-chart', color=color))
        self.ui.stats_tabWidget.setTabIcon(1, qta.icon('mdi.pickaxe', color=color))
        self.ui.stats_tabWidget.setIconSize(QSize(24, 24))

        self.ui.looprequest_search_button.setIcon(qta.icon('fa.search', color=color))
        self.ui.looprequest_search_button.setIconSize(QSize(24, 24))

        self.ui.send_loop_request_button.setIcon(qta.icon('ei.share-alt', color=color))
        self.ui.send_loop_request_button.setIconSize(QSize(24, 24))
        self.ui.send_transfer_request_button.setIcon(qta.icon('ei.share-alt', color=color))
        self.ui.send_transfer_request_button.setIconSize(QSize(24, 24))

        self.ui.lq_pubkey_search_button.setIcon(qta.icon('fa.search', color=color))
        self.ui.lq_pubkey_search_button.setIconSize(QSize(24, 24))

        self.ui.lq_txid_search_button.setIcon(qta.icon('fa.search', color=color))
        self.ui.lq_txid_search_button.setIconSize(QSize(24, 24))

        self.ui.activeloops_search_button.setIcon(qta.icon('fa.search', color=color))
        self.ui.activeloops_search_button.setIconSize(QSize(24, 24))
        self.ui.holderloops_search_button.setIcon(qta.icon('fa.search', color=color))
        self.ui.holderloops_search_button.setIconSize(QSize(24, 24))
        # Contacts page
        self.ui.clear_contact_button.setIcon(qta.icon('ei.broom', color=color))
        self.ui.clear_contact_button.setIconSize(QSize(24, 24))
        self.ui.addcontact_button.setIcon(qta.icon('fa.user-plus', color=color))
        self.ui.addcontact_button.setIconSize(QSize(24, 24))
        self.ui.updatecontact_button.setIcon(qta.icon('fa5s.user-edit', color=color))
        self.ui.updatecontact_button.setIconSize(QSize(24, 24))
        self.ui.deletecontact_button.setIcon(qta.icon('fa5s.user-slash', color=color))
        self.ui.deletecontact_button.setIconSize(QSize(24, 24))
        # Stats
        self.ui.stats_refresh_pushButton.setIcon(qta.icon('mdi.refresh', color=color))
        self.ui.stats_refresh_pushButton.setIconSize(QSize(24, 24))
        self.ui.stats_calculate_pushButton.setIcon(qta.icon('mdi.calculator-variant-outline', color=color))
        self.ui.stats_calculate_pushButton.setIconSize(QSize(24, 24))
        self.ui.export_earning_table_button.setIcon(qta.icon('mdi.file-export-outline', color=color))
        self.ui.export_earning_table_button.setIconSize(QSize(24, 24))
        self.ui.earnings_search_button.setIcon(qta.icon('fa.search', color=color))
        self.ui.earnings_search_button.setIconSize(QSize(24, 24))
        # Market
        self.ui.exchange_market_request_button.setIcon(qta.icon('mdi.arrow-bottom-left-thick', color=color))
        self.ui.exchange_market_request_button.setIconSize(QSize(24, 24))

    def set_font_size(self, size):
        font = QFont()
        font.setPointSize(size)
        self.ui.centralwidget.setFont(font)
        self.ui.menuBar.setFont(font)
        # talbewidget fontsize
        self.ui.addresses_tableWidget.setFont(font)
        self.ui.addresses_tableWidget.horizontalHeader().setFont(font)
        self.ui.addresses_privkey_tableWidget.setFont(font)
        self.ui.addresses_privkey_tableWidget.horizontalHeader().setFont(font)
        self.ui.transactions_tableWidget.setFont(font)
        self.ui.transactions_tableWidget.horizontalHeader().setFont(font)
        self.ui.loop_request_tableWidget.setFont(font)
        self.ui.loop_request_tableWidget.horizontalHeader().setFont(font)
        self.ui.transferrequests_tableWidget.setFont(font)
        self.ui.transferrequests_tableWidget.horizontalHeader().setFont(font)
        self.ui.activeloops_tableWidget.setFont(font)
        self.ui.activeloops_tableWidget.horizontalHeader().setFont(font)
        self.ui.transferableloops_tableWidget.setFont(font)
        self.ui.transferableloops_tableWidget.horizontalHeader().setFont(font)
        self.ui.contacts_tableWidget.setFont(font)
        self.ui.contacts_tableWidget.horizontalHeader().setFont(font)
        self.ui.exchange_market_tableWidget.setFont(font)
        self.ui.exchange_market_tableWidget.horizontalHeader().setFont(font)
        self.ui.earning_stats_tableWidget.setFont(font)
        self.ui.earning_stats_tableWidget.horizontalHeader().setFont(font)
        # label Font size
        # login page labels
        self.ui.local_button.setFont(font)
        self.ui.remote_button.setFont(font)
        self.ui.serveradd_button.setFont(font)
        self.ui.serveredit_button.setFont(font)
        self.ui.serverpw_lineEdit.setFont(font)
        self.ui.remotelogin_label.setFont(font)
        self.ui.connect_button.setFont(font)
        self.ui.add_remotehost_label.setFont(font)
        self.ui.add_serversave_button.setFont(font)
        self.ui.servercancel_button.setFont(font)
        self.ui.add_servername_label.setFont(font)
        self.ui.add_servername_lineEdit.setFont(font)
        self.ui.add_serverusername_label.setFont(font)
        self.ui.add_serverusername_lineEdit.setFont(font)
        self.ui.add_serverip_label.setFont(font)
        self.ui.add_serverip_lineEdit.setFont(font)
        self.ui.edit_serverip_lineEdit.setFont(font)
        self.ui.edit_serverip_label.setFont(font)
        self.ui.edit_serverusername_label.setFont(font)
        self.ui.edit_servername_label.setFont(font)
        self.ui.edit_serverusername_lineEdit.setFont(font)
        self.ui.edit_servername_lineEdit.setFont(font)
        self.ui.edit_serversave_button.setFont(font)
        self.ui.serverdelete_button.setFont(font)
        self.ui.edit_remotehost_label.setFont(font)
        self.ui.home_button.setFont(font)
        self.ui.server_comboBox.setFont(font)
        self.ui.ssh_port_checkBox.setFont(font)
        self.ui.ssh_port_lineEdit.setFont(font)
        # Install Page
        self.ui.sudo_password_lineEdit.setFont(font)
        self.ui.start_install_button.setFont(font)
        self.ui.install_progress_textBrowser.setFont(font)
        self.ui.install_progressBar.setFont(font)
        # mcl page
        self.ui.mcl_tab.tabBar().setFont(font)
        # Side panel Labels
        self.ui.walletsummary_label.setFont(font)
        self.ui.totalnormal_label.setFont(font)
        self.ui.totalnormal_value_label.setFont(font)
        self.ui.totalactivated_label.setFont(font)
        self.ui.totalactivated_value_label.setFont(font)
        self.ui.currentblock_label.setFont(font)
        self.ui.currentblock_value_label.setFont(font)
        self.ui.difficulty_label.setFont(font)
        self.ui.difficulty_value_label.setFont(font)
        self.ui.longestchain_label.setFont(font)
        self.ui.longestchain_value_label.setFont(font)
        self.ui.connections_label.setFont(font)
        self.ui.connections_value_label.setFont(font)
        self.ui.chainstatus_label.setFont(font)
        self.ui.chainstatus_label_value.setFont(font)
        self.ui.chainsync_label.setFont(font)
        self.ui.chainsync_label_value.setFont(font)
        self.ui.getinfo_refresh_button.setFont(font)
        self.ui.staking_label.setFont(font)
        self.ui.mining_label.setFont(font)
        self.ui.cpu_label.setFont(font)
        self.ui.cpu_core_lineEdit.setFont(font)
        self.ui.cpu_core_set_button.setFont(font)
        self.ui.miningstatus_label.setFont(font)
        self.ui.support_pushButton.setFont(font)
        self.ui.coffee_icon_label.setFont(font)
        self.ui.multiply_label.setFont(font)
        self.ui.cup_lineEdit.setFont(font)
        self.ui.copypubkey_button.setFont(font)
        self.ui.copyaddress_button.setFont(font)
        self.ui.fontsize_minus_button.setFont(font)
        self.ui.fontsize_plus_button.setFont(font)
        # Chain tab label
        self.ui.chain_version_label.setFont(font)
        self.ui.privkey_page_button.setFont(font)
        self.ui.addaddress_page_button.setFont(font)
        self.ui.chain_wallet_addresses_label.setFont(font)
        self.ui.stopchain_button.setFont(font)
        self.ui.hide_address_checkBox.setFont(font)
        self.ui.download_blocks_button.setFont(font)
        self.ui.check_fork_button.setFont(font)
        self.ui.update_chain_button.setFont(font)
        self.ui.debug_button.setFont(font)
        self.ui.newaddress_button.setFont(font)
        self.ui.address_seed_button.setFont(font)
        self.ui.add_with_seed_radiobutton.setFont(font)
        self.ui.add_without_seed_radiobutton.setFont(font)
        self.ui.confirm_passphrase_TextEdit.setFont(font)
        self.ui.create_seed_label.setFont(font)
        self.ui.passphrase_TextEdit.setFont(font)
        self.ui.addresspage_back_button.setFont(font)
        self.ui.privatekeypage_back_button.setFont(font)
        self.ui.see_address_privkeys_label.setFont(font)
        self.ui.importprivkey_label.setFont(font)
        self.ui.importprivkey_button.setFont(font)
        self.ui.privkey_lineEdit.setFont(font)
        self.ui.update_chain_textBrowser.setFont(font)
        # Wallet page label
        self.ui.unlock_amount_label.setFont(font)
        self.ui.unlock_amount_value.setFont(font)
        self.ui.unlock_button.setFont(font)
        self.ui.lock_amount_label.setFont(font)
        self.ui.lock_amount_value.setFont(font)
        self.ui.lock_button.setFont(font)
        self.ui.unlock_activeamount_label.setFont(font)
        self.ui.lock_normal_amount_label.setFont(font)
        self.ui.normal_amount_label.setFont(font)
        self.ui.normal_amount_value.setFont(font)
        self.ui.wallet_total_activated_label.setFont(font)
        self.ui.wallet_total_activated_value.setFont(font)
        self.ui.wallet_balance_label.setFont(font)
        self.ui.wallet_total_normal_label.setFont(font)
        self.ui.wallet_total_normal_value.setFont(font)
        self.ui.activated_amount_label.setFont(font)
        self.ui.activated_amount_value.setFont(font)
        self.ui.pubkey_balance_label.setFont(font)
        self.ui.addressamount_refresh_button.setFont(font)
        self.ui.currentpubkey_label.setFont(font)
        self.ui.current_pubkey_value.setFont(font)
        self.ui.currentaddress_label.setFont(font)
        self.ui.currentaddress_value.setFont(font)
        self.ui.refresh_loopinfo_button.setFont(font)
        # Coin send receive page
        self.ui.transaction_startdate_label.setFont(font)
        self.ui.transaction_enddate_label.setFont(font)
        self.ui.transaction_search_button.setFont(font)
        self.ui.transactions_label.setFont(font)
        self.ui.coinreceive_label.setFont(font)
        self.ui.receiver_address_lineEdit.setFont(font)
        self.ui.sending_amount_label.setFont(font)
        self.ui.sending_amount_lineEdit.setFont(font)
        self.ui.coinsend_button.setFont(font)
        self.ui.contacts_address_comboBox.setFont(font)
        self.ui.receiver_address_label.setFont(font)
        self.ui.coinsend_label.setFont(font)
        self.ui.qrcode_button.setFont(font)
        self.ui.transactions_startdate_dateTimeEdit.setFont(font)
        self.ui.transactions_startdate_dateTimeEdit.calendarWidget().setFont(font)
        self.ui.transactions_endtdate_dateTimeEdit.setFont(font)
        self.ui.transactions_endtdate_dateTimeEdit.calendarWidget().setFont(font)
        # Creditloops page
        self.ui.creditloop_tabWidget.tabBar().setFont(font)
        # Incoming loop request
        self.ui.looprequest_search_button.setFont(font)
        self.ui.requestdate_label.setFont(font)
        self.ui.request_dateTimeEdit.setFont(font)
        self.ui.request_dateTimeEdit.calendarWidget().setFont(font)
        self.ui.request_date_checkBox.setFont(font)
        self.ui.loop_request_label.setFont(font)
        self.ui.transferrequests_label.setFont(font)
        self.ui.looprequest_otherpk_radioButton.setFont(font)
        self.ui.looprequest_currentpk_radioButton.setFont(font)
        self.ui.looprequest_otherpk_lineEdit.setFont(font)
        self.ui.contactpk_otherpk_looprequest_comboBox.setFont(font)
        # make loop request
        self.ui.create_loop_request_label.setFont(font)
        self.ui.send_loop_request_button.setFont(font)
        self.ui.make_credit_loop_amount_label.setFont(font)
        self.ui.make_credit_loop_amount_lineEdit.setFont(font)
        self.ui.make_credit_loop_matures_label.setFont(font)
        self.ui.make_credit_loop_matures_dateTimeEdit.setFont(font)
        self.ui.make_credit_loop_matures_dateTimeEdit.calendarWidget().setFont(font)
        self.ui.make_credit_loop_currency_label.setFont(font)
        self.ui.make_credit_loop_currency_value_label.setFont(font)
        self.ui.make_credit_loop_senderpubkey_label.setFont(font)
        self.ui.make_credit_loop_senderpubkey_lineEdit.setFont(font)
        self.ui.contactpk_makeloop_comboBox.setFont(font)
        self.ui.create_transfer_request_label.setFont(font)
        self.ui.transfer_senderpubkey_label.setFont(font)
        self.ui.transfer_senderpubkey_lineEdit.setFont(font)
        self.ui.send_transfer_request_button.setFont(font)
        self.ui.transfer_baton_label.setFont(font)
        self.ui.transfer_baton_lineEdit.setFont(font)
        self.ui.contactpk_transferrequest_comboBox.setFont(font)
        self.ui.total_issuer_loop_amount_label.setFont(font)

        # Active Loops
        self.ui.Issuerloops_label.setFont(font)
        self.ui.total_transferrable_loop_amount_label.setFont(font)
        self.ui.total_transferrable_loop_amount_label_value.setFont(font)
        self.ui.numberof_transferrable_loop_amount_label.setFont(font)
        self.ui.numberof_transferrable_loop_amount_label_value.setFont(font)
        self.ui.holderloops_closed_amount_label.setFont(font)
        self.ui.holderloops_closed_amount_label_value.setFont(font)
        self.ui.holderloops_closed_number_label.setFont(font)
        self.ui.holderloops_closed_number_label_value.setFont(font)
        self.ui.holderloops_search_button.setFont(font)
        self.ui.transferableloops_label.setFont(font)
        self.ui.activeloops_search_button.setFont(font)
        self.ui.total_issuer_loop_amount_label_value.setFont(font)
        self.ui.activeloops_pending_number_label.setFont(font)
        self.ui.activeloops_pending_number_value_label.setFont(font)
        self.ui.closedloops_total_amount_label.setFont(font)
        self.ui.closedloops_total_amount_value_label.setFont(font)
        self.ui.closedloops_total_number_label.setFont(font)
        self.ui.closedloops_total_number_value_label.setFont(font)
        self.ui.activeloops_total_amount_label.setFont(font)
        self.ui.activeloops_total_amount_value_label.setFont(font)
        self.ui.numberof_total_activeloops_label.setFont(font)
        self.ui.numberof_total_activeloops_label_value.setFont(font)
        self.ui.my_stats_normal_label.setFont(font)
        self.ui.my_stats_normal_label_value.setFont(font)
        self.ui.my_stats_activated_label.setFont(font)
        self.ui.my_stats_activated_label_value.setFont(font)
        self.ui.my_stats_inloops_label.setFont(font)
        self.ui.my_stats_inloops_label_value.setFont(font)
        # Loop queries
        self.ui.loopqueries_pubkey_label.setFont(font)
        self.ui.loopqueries_pubkey_lineEdit.setFont(font)
        self.ui.lq_pubkey_search_button.setFont(font)
        self.ui.lq_pubkeynormalamount_label.setFont(font)
        self.ui.lq_pubkeynormalamount_value_label.setFont(font)
        self.ui.lq_pubkeyclosedloopamount_label.setFont(font)
        self.ui.lq_pubkeyclosedloopamount_value_label.setFont(font)
        self.ui.lq_activeloopno_label.setFont(font)
        self.ui.lq_activeloopno_value_label.setFont(font)
        self.ui.lq_pubkeyactivatedamount_label.setFont(font)
        self.ui.lq_pubkeyactivatedamount_value_label.setFont(font)
        self.ui.lq_closedloopno_label.setFont(font)
        self.ui.lq_closedloopno_value_label.setFont(font)
        self.ui.lq_pubkeyloopamount_label.setFont(font)
        self.ui.lq_pubkeyloopamount_value_label.setFont(font)
        self.ui.lq_pubkey_address_label.setFont(font)
        self.ui.lq_pubkey_address_label_value.setFont(font)
        self.ui.loopquery_transfercount_label.setFont(font)
        self.ui.loopquery_transfercount_value.setFont(font)
        self.ui.loopquery_matures_label.setFont(font)
        self.ui.loopquery_matures_value.setFont(font)
        self.ui.loopquery_currency_label.setFont(font)
        self.ui.loopquery_currency_value.setFont(font)
        self.ui.loopquery_amount_label.setFont(font)
        self.ui.loopquery_amount_value.setFont(font)
        self.ui.loopquery_issuer_label.setFont(font)
        self.ui.loopquery_issuer_value.setFont(font)
        self.ui.loopquery_baton_label.setFont(font)
        self.ui.loopquery_baton_value.setFont(font)
        self.ui.loopquery_batonpk_label.setFont(font)
        self.ui.loopquery_batonpk_value.setFont(font)
        self.ui.loopquery_info_label.setFont(font)
        self.ui.loopsearch_txid_label.setFont(font)
        self.ui.loopsearch_txid_lineEdit.setFont(font)
        self.ui.lq_txid_search_button.setFont(font)
        # Contacts Page
        self.ui.updatecontact_button.setFont(font)
        self.ui.addcontact_button.setFont(font)
        self.ui.contactname_label.setFont(font)
        self.ui.contactname_lineEdit.setFont(font)
        self.ui.contactaddress_label.setFont(font)
        self.ui.contactaddress_lineEdit.setFont(font)
        self.ui.contactpubkey_label.setFont(font)
        self.ui.contactpubkey_lineEdit.setFont(font)
        self.ui.contactgroup_lineEdit.setFont(font)
        self.ui.contactgroup_label.setFont(font)
        self.ui.deletecontact_button.setFont(font)
        self.ui.clear_contact_button.setFont(font)
        # Stats Page
        self.ui.stats_amount_in_activated_label.setFont(font)
        self.ui.stats_amount_in_activated_lineEdit.setFont(font)
        self.ui.stats_amount_in_loops_label.setFont(font)
        self.ui.stats_amount_in_loops_lineEdit.setFont(font)
        self.ui.stats_estimated_staking_label.setFont(font)
        self.ui.stats_estimated_staking_label_value.setFont(font)
        self.ui.stats_calculate_pushButton.setFont(font)
        self.ui.stats_height_label.setFont(font)
        self.ui.stats_height_value_label.setFont(font)
        self.ui.stats_in_loops_label.setFont(font)
        self.ui.stats_in_loops_label_value.setFont(font)
        self.ui.stats_activated_label.setFont(font)
        self.ui.stats_activated_label_value.setFont(font)
        self.ui.stats_normal_label.setFont(font)
        self.ui.stats_normal_label_value.setFont(font)
        self.ui.stats_label.setFont(font)
        self.ui.earningstat_table_label.setFont(font)
        self.ui.earnings_search_button.setFont(font)
        self.ui.earning_startdate_label.setFont(font)
        self.ui.earning_start_dateTimeEdit.setFont(font)
        self.ui.earning_start_dateTimeEdit.calendarWidget().setFont(font)
        self.ui.earning_stopdate_label.setFont(font)
        self.ui.earning_stop_dateTimeEdit.setFont(font)
        self.ui.earning_stop_dateTimeEdit.calendarWidget().setFont(font)
        self.ui.total_earnings_label.setFont(font)
        self.ui.total_earning_label.setFont(font)
        self.ui.total_earning_value.setFont(font)
        self.ui.normal_earning_label.setFont(font)
        self.ui.normal_earning_value.setFont(font)
        self.ui.activated_earning_label.setFont(font)
        self.ui.activated_earning_value.setFont(font)
        # Market Page
        self.ui.usd_amount_lineEdit.setFont(font)
        self.ui.convert_mcl_label.setFont(font)
        self.ui.exchange_label_icon.setFont(font)
        self.ui.mcl_amount_lineEdit.setFont(font)
        self.ui.convert_usd_label.setFont(font)
        self.ui.mcl_usd_calculator_label.setFont(font)
        self.ui.exchange_market_label.setFont(font)
        self.ui.ticker_volume_label.setFont(font)
        self.ui.ticker_volume_label_value.setFont(font)
        self.ui.ticker_1hour_label.setFont(font)
        self.ui.ticker_1hour_label_value.setFont(font)
        self.ui.ticker_1week_label.setFont(font)
        self.ui.ticker_1week_label_value.setFont(font)
        self.ui.ticker_price_label.setFont(font)
        self.ui.ticker_price_label_value.setFont(font)
        self.ui.ticker_24hour_label.setFont(font)
        self.ui.ticker_24hour_label_value.setFont(font)
        self.ui.ticker_1month_label.setFont(font)
        self.ui.ticker_1month_label_value.setFont(font)
        self.ui.exchange_market_comboBox.setFont(font)
        self.ui.market_fiat_comboBox.setFont(font)
        # header label fontsize
        font.setPointSize(size + 4)
        self.ui.login_label.setFont(font)
        self.ui.remotelogin_label.setFont(font)
        self.ui.add_remotehost_label.setFont(font)
        self.ui.edit_remotehost_label.setFont(font)
        # Menu items font
        font.setPointSize(size - 1)
        self.ui.host_name_label.setFont(font)
        self.ui.actionQuit.setFont(font)
        self.ui.actionAbout.setFont(font)
        self.ui.actionLogout.setFont(font)
        # self.ui.actionAppearances.setFont(font)
        self.ui.actionToolbar.setFont(font)
        self.ui.actionPreferences.setFont(font)
        self.ui.actionConsole.setFont(font)
        self.ui.actionCheck_for_Update.setFont(font)
        # self.ui.actionLanguage_Selection.setFont(font)
        self.ui.menuHelp.setFont(font)
        self.ui.actionSee_Log_File.setFont(font)
        self.ui.actionSee_chain_Log_File.setFont(font)
        # smaller fontsize
        font.setPointSize(size - 2)
        self.ui.login_message_label.setFont(font)
        self.ui.bottom_message_label.setFont(font)
        self.ui.last_update_label.setFont(font)
        self.ui.mining_button.setFont(font)
        self.ui.staking_button.setFont(font)


class ToggleSwitch(QPushButton):
    def __init__(self, parent=None):
        super().__init__(parent)

        self.setCheckable(True)
        self.setMinimumWidth(66)
        self.setMinimumHeight(22)

    def paintEvent(self, event):
        label = "ON" if self.isChecked() else "OFF"
        bg_color = Qt.green if self.isChecked() else Qt.red

        radius = 10
        width = 32
        center = self.rect().center()

        painter = QPainter(self)
        painter.setRenderHint(QPainter.Antialiasing)
        painter.translate(center)
        painter.setBrush(QColor(0, 0, 0))

        pen = QPen(Qt.black)
        pen.setWidth(2)
        painter.setPen(pen)

        painter.drawRoundedRect(QRect(-width, -radius, 2 * width, 2 * radius), radius, radius)
        painter.setBrush(QBrush(bg_color))
        sw_rect = QRect(-radius, -radius, width + radius, 2 * radius)
        if not self.isChecked():
            sw_rect.moveLeft(-width)
        painter.drawRoundedRect(sw_rect, radius, radius)
        painter.drawText(sw_rect, Qt.AlignCenter, label)
