linux_d = './marmarad '
windows_d = 'marmarad.exe '
linux_cli = './marmara-cli '
windows_cli = 'marmara-cli.exe '
marmarad = ''
getinfo = "getinfo"
validateaddress = 'validateaddress'
getaddressesbyaccount = 'getaddressesbyaccount'
listaddressgroupings = 'listaddressgroupings'
setpubkey = 'setpubkey'
getnewaddress = 'getnewaddress'
stop = 'stop'
marmaraunlock = 'marmaraunlock'
marmaralock = 'marmaralock'
getbalance = 'getbalance'
getgenerate = 'getgenerate'
setgenerate = 'setgenerate'  # + True "number" or False
getaddressbalance = 'getaddressbalance'  # +  '{"addresses": ["address"]}'
convertpassphrase = 'convertpassphrase'  # + "agamapassphrase"
importprivkey = 'importprivkey'  # + "wifkey"
dumpprivkey = 'dumpprivkey'  # + "address"
marmarainfo = 'marmarainfo'  # firstheight + lastheight + minamount + maxamount + pubkey
sendrawtransaction = 'sendrawtransaction'  # + hex
marmarareceivelist = 'marmarareceivelist'  # + pubkey + maxage
sendtoaddress = 'sendtoaddress'  # + amount
marmaracreditloop = 'marmaracreditloop'  # + txid
marmarareceive = 'marmarareceive'  # case 1: + senderpk + amount + currency + matures + '{"avalcount":"n"}' case 2:
# senderpk batontxid '{"avalcount":"n"}'
marmaratransfer = 'marmaratransfer'  # + receiverpk + '{"avalcount":"n"}' + requesttxid
marmaraissue = 'marmaraissue'  # receiverpk + '{"avalcount":"n", "autosettlement":"true"|"false",
# "autoinsurance":"true"|"false", "disputeexpires":"offset", "EscrowOn":"true"|"false", "BlockageAmount":"amount" }'
# + requesttxid
marmaraholderloops = 'marmaraholderloops'  # firstheight + lastheight + minamount + maxamount + pk + [currency]
getaddresstxids = 'getaddresstxids'  # '{"addresses": ["address"], "start": 799712,  "end": 799734}'
marmaralistactivatedaddresses = 'marmaralistactivatedaddresses'
gettransaction = 'gettransaction'  # + txid
getblock = 'getblock'  # + block
getrawtransaction = 'getrawtransaction'  # + txid
decoderawtransaction = 'decoderawtransaction'  # rawtxid
