# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtguidesign.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1024, 768)
        font = QtGui.QFont()
        font.setPointSize(16)
        MainWindow.setFont(font)
        MainWindow.setWindowTitle("Marmara Connector")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.main_tab = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.main_tab.setFont(font)
        self.main_tab.setObjectName("main_tab")
        self.login_tab = QtWidgets.QWidget()
        self.login_tab.setObjectName("login_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.login_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 4, 1, 1, 1)
        self.login_frame = QtWidgets.QFrame(self.login_tab)
        self.login_frame.setAcceptDrops(False)
        self.login_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_frame.setObjectName("login_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.login_frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.login_stackedWidget = QtWidgets.QStackedWidget(self.login_frame)
        self.login_stackedWidget.setObjectName("login_stackedWidget")
        self.hostselection_page = QtWidgets.QWidget()
        self.hostselection_page.setObjectName("hostselection_page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.hostselection_page)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.hostselection_frame = QtWidgets.QFrame(self.hostselection_page)
        self.hostselection_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.hostselection_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.hostselection_frame.setObjectName("hostselection_frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.hostselection_frame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.remote_button = QtWidgets.QPushButton(self.hostselection_frame)
        self.remote_button.setMinimumSize(QtCore.QSize(100, 70))
        self.remote_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.remote_button.setFont(font)
        self.remote_button.setObjectName("remote_button")
        self.gridLayout_6.addWidget(self.remote_button, 1, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 1, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem3, 0, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem5, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem6, 2, 1, 1, 1)
        self.local_button = QtWidgets.QPushButton(self.hostselection_frame)
        self.local_button.setMinimumSize(QtCore.QSize(100, 70))
        self.local_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.local_button.setFont(font)
        self.local_button.setIconSize(QtCore.QSize(32, 32))
        self.local_button.setObjectName("local_button")
        self.gridLayout_6.addWidget(self.local_button, 1, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem7, 1, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem8, 2, 3, 1, 1)
        self.gridLayout_5.addWidget(self.hostselection_frame, 1, 0, 1, 5)
        self.selecthost_frame = QtWidgets.QFrame(self.hostselection_page)
        self.selecthost_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.selecthost_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.selecthost_frame.setObjectName("selecthost_frame")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.selecthost_frame)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.login_label = QtWidgets.QLabel(self.selecthost_frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.login_label.setFont(font)
        self.login_label.setAlignment(QtCore.Qt.AlignCenter)
        self.login_label.setObjectName("login_label")
        self.gridLayout_15.addWidget(self.login_label, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.selecthost_frame, 0, 0, 1, 5)
        self.login_stackedWidget.addWidget(self.hostselection_page)
        self.hostlogin_page = QtWidgets.QWidget()
        self.hostlogin_page.setObjectName("hostlogin_page")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.hostlogin_page)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.serverpw_frame = QtWidgets.QFrame(self.hostlogin_page)
        self.serverpw_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.serverpw_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.serverpw_frame.setObjectName("serverpw_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.serverpw_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.serverpw_lineEdit = QtWidgets.QLineEdit(self.serverpw_frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.serverpw_lineEdit.setFont(font)
        self.serverpw_lineEdit.setObjectName("serverpw_lineEdit")
        self.horizontalLayout.addWidget(self.serverpw_lineEdit)
        self.gridLayout_7.addWidget(self.serverpw_frame, 4, 0, 1, 2)
        self.serverconnect_frame = QtWidgets.QFrame(self.hostlogin_page)
        self.serverconnect_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.serverconnect_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.serverconnect_frame.setObjectName("serverconnect_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.serverconnect_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.connect_button = QtWidgets.QPushButton(self.serverconnect_frame)
        self.connect_button.setMinimumSize(QtCore.QSize(0, 30))
        self.connect_button.setMaximumSize(QtCore.QSize(80, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.connect_button.setFont(font)
        self.connect_button.setObjectName("connect_button")
        self.horizontalLayout_2.addWidget(self.connect_button)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.gridLayout_7.addWidget(self.serverconnect_frame, 5, 0, 1, 2)
        self.serverselection_frame = QtWidgets.QFrame(self.hostlogin_page)
        self.serverselection_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.serverselection_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.serverselection_frame.setObjectName("serverselection_frame")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.serverselection_frame)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.serveradd_button = QtWidgets.QPushButton(self.serverselection_frame)
        self.serveradd_button.setMinimumSize(QtCore.QSize(0, 0))
        self.serveradd_button.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.serveradd_button.setFont(font)
        self.serveradd_button.setObjectName("serveradd_button")
        self.gridLayout_20.addWidget(self.serveradd_button, 0, 1, 1, 1)
        self.serveredit_button = QtWidgets.QPushButton(self.serverselection_frame)
        self.serveredit_button.setMinimumSize(QtCore.QSize(0, 0))
        self.serveredit_button.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.serveredit_button.setFont(font)
        self.serveredit_button.setObjectName("serveredit_button")
        self.gridLayout_20.addWidget(self.serveredit_button, 1, 1, 1, 1)
        self.server_comboBox = QtWidgets.QComboBox(self.serverselection_frame)
        self.server_comboBox.setMinimumSize(QtCore.QSize(250, 60))
        self.server_comboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.server_comboBox.setFont(font)
        self.server_comboBox.setEditable(False)
        self.server_comboBox.setObjectName("server_comboBox")
        self.gridLayout_20.addWidget(self.server_comboBox, 0, 0, 2, 1)
        self.gridLayout_7.addWidget(self.serverselection_frame, 1, 0, 1, 2)
        self.remoteloginlabel_frame = QtWidgets.QFrame(self.hostlogin_page)
        self.remoteloginlabel_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.remoteloginlabel_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.remoteloginlabel_frame.setObjectName("remoteloginlabel_frame")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.remoteloginlabel_frame)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.remotelogin_label = QtWidgets.QLabel(self.remoteloginlabel_frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.remotelogin_label.setFont(font)
        self.remotelogin_label.setAlignment(QtCore.Qt.AlignCenter)
        self.remotelogin_label.setObjectName("remotelogin_label")
        self.gridLayout_19.addWidget(self.remotelogin_label, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.remoteloginlabel_frame, 0, 0, 1, 2)
        self.login_stackedWidget.addWidget(self.hostlogin_page)
        self.hostedit_page = QtWidgets.QWidget()
        self.hostedit_page.setObjectName("hostedit_page")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.hostedit_page)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.add_serversave_frame = QtWidgets.QFrame(self.hostedit_page)
        self.add_serversave_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.add_serversave_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.add_serversave_frame.setObjectName("add_serversave_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.add_serversave_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.servercancel_button = QtWidgets.QPushButton(self.add_serversave_frame)
        self.servercancel_button.setMaximumSize(QtCore.QSize(80, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.servercancel_button.setFont(font)
        self.servercancel_button.setObjectName("servercancel_button")
        self.gridLayout_2.addWidget(self.servercancel_button, 0, 2, 1, 1)
        self.add_serversave_button = QtWidgets.QPushButton(self.add_serversave_frame)
        self.add_serversave_button.setMaximumSize(QtCore.QSize(80, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.add_serversave_button.setFont(font)
        self.add_serversave_button.setObjectName("add_serversave_button")
        self.gridLayout_2.addWidget(self.add_serversave_button, 0, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.add_serversave_frame, 4, 0, 1, 2)
        self.add_remotehostlabel_frame = QtWidgets.QFrame(self.hostedit_page)
        self.add_remotehostlabel_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.add_remotehostlabel_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.add_remotehostlabel_frame.setObjectName("add_remotehostlabel_frame")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.add_remotehostlabel_frame)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.add_remotehost_label = QtWidgets.QLabel(self.add_remotehostlabel_frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.add_remotehost_label.setFont(font)
        self.add_remotehost_label.setAlignment(QtCore.Qt.AlignCenter)
        self.add_remotehost_label.setObjectName("add_remotehost_label")
        self.gridLayout_21.addWidget(self.add_remotehost_label, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.add_remotehostlabel_frame, 0, 0, 1, 2)
        self.add_serversettings_frame = QtWidgets.QFrame(self.hostedit_page)
        self.add_serversettings_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.add_serversettings_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.add_serversettings_frame.setObjectName("add_serversettings_frame")
        self.formLayout_3 = QtWidgets.QFormLayout(self.add_serversettings_frame)
        self.formLayout_3.setObjectName("formLayout_3")
        self.add_servername_label = QtWidgets.QLabel(self.add_serversettings_frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.add_servername_label.setFont(font)
        self.add_servername_label.setObjectName("add_servername_label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.add_servername_label)
        self.add_servername_lineEdit = QtWidgets.QLineEdit(self.add_serversettings_frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.add_servername_lineEdit.setFont(font)
        self.add_servername_lineEdit.setObjectName("add_servername_lineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.add_servername_lineEdit)
        self.add_serverusername_label = QtWidgets.QLabel(self.add_serversettings_frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.add_serverusername_label.setFont(font)
        self.add_serverusername_label.setObjectName("add_serverusername_label")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.add_serverusername_label)
        self.add_serverusername_lineEdit = QtWidgets.QLineEdit(self.add_serversettings_frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.add_serverusername_lineEdit.setFont(font)
        self.add_serverusername_lineEdit.setObjectName("add_serverusername_lineEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.add_serverusername_lineEdit)
        self.add_serverip_label = QtWidgets.QLabel(self.add_serversettings_frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.add_serverip_label.setFont(font)
        self.add_serverip_label.setObjectName("add_serverip_label")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.add_serverip_label)
        self.add_serverip_lineEdit = QtWidgets.QLineEdit(self.add_serversettings_frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.add_serverip_lineEdit.setFont(font)
        self.add_serverip_lineEdit.setObjectName("add_serverip_lineEdit")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.add_serverip_lineEdit)
        self.gridLayout_13.addWidget(self.add_serversettings_frame, 1, 0, 1, 2)
        self.login_stackedWidget.addWidget(self.hostedit_page)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.edit_remotehostlabel_frame = QtWidgets.QFrame(self.page)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.edit_remotehostlabel_frame.setFont(font)
        self.edit_remotehostlabel_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.edit_remotehostlabel_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.edit_remotehostlabel_frame.setObjectName("edit_remotehostlabel_frame")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.edit_remotehostlabel_frame)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.edit_remotehost_label = QtWidgets.QLabel(self.edit_remotehostlabel_frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.edit_remotehost_label.setFont(font)
        self.edit_remotehost_label.setAlignment(QtCore.Qt.AlignCenter)
        self.edit_remotehost_label.setObjectName("edit_remotehost_label")
        self.gridLayout_22.addWidget(self.edit_remotehost_label, 0, 0, 1, 1)
        self.gridLayout_23.addWidget(self.edit_remotehostlabel_frame, 0, 0, 1, 1)
        self.edit_serversettings_frame = QtWidgets.QFrame(self.page)
        self.edit_serversettings_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.edit_serversettings_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.edit_serversettings_frame.setObjectName("edit_serversettings_frame")
        self.formLayout_2 = QtWidgets.QFormLayout(self.edit_serversettings_frame)
        self.formLayout_2.setObjectName("formLayout_2")
        self.edit_servername_label = QtWidgets.QLabel(self.edit_serversettings_frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.edit_servername_label.setFont(font)
        self.edit_servername_label.setObjectName("edit_servername_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.edit_servername_label)
        self.edit_servername_lineEdit = QtWidgets.QLineEdit(self.edit_serversettings_frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.edit_servername_lineEdit.setFont(font)
        self.edit_servername_lineEdit.setObjectName("edit_servername_lineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edit_servername_lineEdit)
        self.edit_serverusername_label = QtWidgets.QLabel(self.edit_serversettings_frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.edit_serverusername_label.setFont(font)
        self.edit_serverusername_label.setObjectName("edit_serverusername_label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.edit_serverusername_label)
        self.edit_serverusername_lineEdit = QtWidgets.QLineEdit(self.edit_serversettings_frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.edit_serverusername_lineEdit.setFont(font)
        self.edit_serverusername_lineEdit.setObjectName("edit_serverusername_lineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edit_serverusername_lineEdit)
        self.edit_serverip_label = QtWidgets.QLabel(self.edit_serversettings_frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.edit_serverip_label.setFont(font)
        self.edit_serverip_label.setObjectName("edit_serverip_label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.edit_serverip_label)
        self.edit_serverip_lineEdit = QtWidgets.QLineEdit(self.edit_serversettings_frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.edit_serverip_lineEdit.setFont(font)
        self.edit_serverip_lineEdit.setObjectName("edit_serverip_lineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.edit_serverip_lineEdit)
        self.gridLayout_23.addWidget(self.edit_serversettings_frame, 1, 0, 1, 1)
        self.edit_serversave_frame = QtWidgets.QFrame(self.page)
        self.edit_serversave_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.edit_serversave_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.edit_serversave_frame.setObjectName("edit_serversave_frame")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.edit_serversave_frame)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.serverdelete_button = QtWidgets.QPushButton(self.edit_serversave_frame)
        self.serverdelete_button.setMaximumSize(QtCore.QSize(80, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.serverdelete_button.setFont(font)
        self.serverdelete_button.setObjectName("serverdelete_button")
        self.gridLayout_24.addWidget(self.serverdelete_button, 0, 2, 1, 1)
        self.edit_serversave_button = QtWidgets.QPushButton(self.edit_serversave_frame)
        self.edit_serversave_button.setMaximumSize(QtCore.QSize(80, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.edit_serversave_button.setFont(font)
        self.edit_serversave_button.setObjectName("edit_serversave_button")
        self.gridLayout_24.addWidget(self.edit_serversave_button, 0, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_24.addItem(spacerItem12, 0, 0, 1, 1)
        self.gridLayout_23.addWidget(self.edit_serversave_frame, 2, 0, 1, 1)
        self.login_stackedWidget.addWidget(self.page)
        self.gridLayout_3.addWidget(self.login_stackedWidget, 3, 1, 1, 1)
        self.gridLayout_4.addWidget(self.login_frame, 1, 1, 1, 1)
        self.language_frame = QtWidgets.QFrame(self.login_tab)
        self.language_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.language_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.language_frame.setObjectName("language_frame")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.language_frame)
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem13, 0, 1, 1, 1)
        self.home_button = QtWidgets.QPushButton(self.language_frame)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../../../MarmaraQt/src/main/resources/base/images/exit_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_button.setIcon(icon)
        self.home_button.setObjectName("home_button")
        self.gridLayout_10.addWidget(self.home_button, 0, 0, 1, 1)
        self.lang_comboBox = QtWidgets.QComboBox(self.language_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lang_comboBox.setFont(font)
        self.lang_comboBox.setObjectName("lang_comboBox")
        self.gridLayout_10.addWidget(self.lang_comboBox, 0, 3, 1, 1)
        self.language_label = QtWidgets.QLabel(self.language_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.language_label.setFont(font)
        self.language_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.language_label.setObjectName("language_label")
        self.gridLayout_10.addWidget(self.language_label, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.language_frame, 2, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem14, 0, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(319, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem15, 1, 0, 1, 1)
        self.login_message_label = QtWidgets.QLabel(self.login_tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.login_message_label.setFont(font)
        self.login_message_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_message_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_message_label.setText("")
        self.login_message_label.setObjectName("login_message_label")
        self.gridLayout_4.addWidget(self.login_message_label, 3, 1, 1, 1)
        self.main_tab.addTab(self.login_tab, "")
        self.marmara_tab = QtWidgets.QWidget()
        self.marmara_tab.setObjectName("marmara_tab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.marmara_tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.frame_2 = QtWidgets.QFrame(self.marmara_tab)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_23 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_12.addWidget(self.label_23, 0, 0, 1, 3)
        self.label_25 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_12.addWidget(self.label_25, 2, 1, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_12.addWidget(self.label_15, 2, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_12.addWidget(self.label_20, 3, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_12.addWidget(self.label_22, 3, 1, 1, 2)
        self.gridLayout_9.addWidget(self.frame_5, 4, 0, 1, 2)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_16.addWidget(self.pushButton, 0, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_16.addWidget(self.label_2, 1, 0, 1, 2)
        self.gridLayout_9.addWidget(self.frame_3, 0, 0, 1, 2)
        self.frame_10 = QtWidgets.QFrame(self.frame_2)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_12 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_17.addWidget(self.label_12, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_17.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_17.addWidget(self.label_16, 0, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_17.addWidget(self.pushButton_7, 1, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_17.addWidget(self.label_24, 1, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_17.addWidget(self.label_18, 5, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_17.addWidget(self.label_17, 0, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_17.addWidget(self.pushButton_4, 3, 1, 1, 1)
        self.gridLayout_9.addWidget(self.frame_10, 3, 0, 1, 2)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_14.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_14.addWidget(self.label_21, 1, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_14.addWidget(self.label_19, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_14.addWidget(self.pushButton_3, 1, 1, 1, 1)
        self.gridLayout_9.addWidget(self.frame_6, 7, 0, 1, 2)
        self.frame_9 = QtWidgets.QFrame(self.frame_2)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.chainsync_button = QtWidgets.QPushButton(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chainsync_button.setFont(font)
        self.chainsync_button.setText("")
        self.chainsync_button.setObjectName("chainsync_button")
        self.gridLayout_11.addWidget(self.chainsync_button, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_11.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_11.addWidget(self.label_9, 6, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_11.addWidget(self.label_6, 7, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_11.addWidget(self.label_10, 6, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_11.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_11.addWidget(self.label_8, 5, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_11.addWidget(self.label_11, 7, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_11.addWidget(self.label_28, 8, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_11.addWidget(self.label_27, 8, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_11.addWidget(self.label_5, 0, 0, 1, 1)
        self.chainstatus_button = QtWidgets.QPushButton(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chainstatus_button.setFont(font)
        self.chainstatus_button.setText("")
        self.chainstatus_button.setObjectName("chainstatus_button")
        self.gridLayout_11.addWidget(self.chainstatus_button, 0, 1, 1, 1)
        self.gridLayout_9.addWidget(self.frame_9, 2, 0, 1, 2)
        self.gridLayout_8.addWidget(self.frame_2, 0, 1, 1, 1)
        self.mcl_tab = QtWidgets.QTabWidget(self.marmara_tab)
        self.mcl_tab.setMaximumSize(QtCore.QSize(735, 675))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mcl_tab.setFont(font)
        self.mcl_tab.setTabPosition(QtWidgets.QTabWidget.North)
        self.mcl_tab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.mcl_tab.setElideMode(QtCore.Qt.ElideNone)
        self.mcl_tab.setDocumentMode(False)
        self.mcl_tab.setTabsClosable(False)
        self.mcl_tab.setMovable(False)
        self.mcl_tab.setTabBarAutoHide(False)
        self.mcl_tab.setObjectName("mcl_tab")
        self.chain_tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chain_tab.setFont(font)
        self.chain_tab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chain_tab.setStyleSheet("")
        self.chain_tab.setObjectName("chain_tab")
        self.mcl_tab.addTab(self.chain_tab, "")
        self.wallet_tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(12)
        self.wallet_tab.setFont(font)
        self.wallet_tab.setObjectName("wallet_tab")
        self.mcl_tab.addTab(self.wallet_tab, "")
        self.credit_tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(12)
        self.credit_tab.setFont(font)
        self.credit_tab.setObjectName("credit_tab")
        self.mcl_tab.addTab(self.credit_tab, "")
        self.person_tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(12)
        self.person_tab.setFont(font)
        self.person_tab.setObjectName("person_tab")
        self.mcl_tab.addTab(self.person_tab, "")
        self.settings_tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(12)
        self.settings_tab.setFont(font)
        self.settings_tab.setObjectName("settings_tab")
        self.mcl_tab.addTab(self.settings_tab, "")
        self.exit_tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exit_tab.setFont(font)
        self.exit_tab.setObjectName("exit_tab")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.exit_tab)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.mcl_tab.addTab(self.exit_tab, "")
        self.gridLayout_8.addWidget(self.mcl_tab, 0, 0, 1, 1)
        self.bottom_message_label = QtWidgets.QLabel(self.marmara_tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bottom_message_label.setFont(font)
        self.bottom_message_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_message_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_message_label.setText("")
        self.bottom_message_label.setObjectName("bottom_message_label")
        self.gridLayout_8.addWidget(self.bottom_message_label, 1, 0, 1, 2)
        self.main_tab.addTab(self.marmara_tab, "")
        self.install_tab = QtWidgets.QWidget()
        self.install_tab.setObjectName("install_tab")
        self.main_tab.addTab(self.install_tab, "")
        self.gridLayout.addWidget(self.main_tab, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.main_tab.setCurrentIndex(0)
        self.login_stackedWidget.setCurrentIndex(1)
        self.mcl_tab.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.remote_button.setText(_translate("MainWindow", "Remote"))
        self.local_button.setText(_translate("MainWindow", "Local"))
        self.login_label.setText(_translate("MainWindow", "Select Host "))
        self.serverpw_lineEdit.setPlaceholderText(_translate("MainWindow", "Server Login password"))
        self.connect_button.setText(_translate("MainWindow", "Connect"))
        self.serveradd_button.setText(_translate("MainWindow", "Add"))
        self.serveredit_button.setText(_translate("MainWindow", "Edit"))
        self.remotelogin_label.setText(_translate("MainWindow", "Login Remote Host"))
        self.servercancel_button.setText(_translate("MainWindow", "Cancel"))
        self.add_serversave_button.setText(_translate("MainWindow", "Save"))
        self.add_remotehost_label.setText(_translate("MainWindow", "Add Remote Host"))
        self.add_servername_label.setText(_translate("MainWindow", "Name"))
        self.add_servername_lineEdit.setPlaceholderText(_translate("MainWindow", "Name"))
        self.add_serverusername_label.setText(_translate("MainWindow", "Username"))
        self.add_serverusername_lineEdit.setPlaceholderText(_translate("MainWindow", "Server Username"))
        self.add_serverip_label.setText(_translate("MainWindow", "IP Address"))
        self.add_serverip_lineEdit.setPlaceholderText(_translate("MainWindow", "000.000.000.000"))
        self.edit_remotehost_label.setText(_translate("MainWindow", "Edit Remote Host"))
        self.edit_servername_label.setText(_translate("MainWindow", "Name"))
        self.edit_servername_lineEdit.setPlaceholderText(_translate("MainWindow", "Name"))
        self.edit_serverusername_label.setText(_translate("MainWindow", "Username"))
        self.edit_serverusername_lineEdit.setPlaceholderText(_translate("MainWindow", "Server Username"))
        self.edit_serverip_label.setText(_translate("MainWindow", "IP Address"))
        self.edit_serverip_lineEdit.setPlaceholderText(_translate("MainWindow", "000.000.000.000"))
        self.serverdelete_button.setText(_translate("MainWindow", "Delete"))
        self.edit_serversave_button.setText(_translate("MainWindow", "Save"))
        self.home_button.setText(_translate("MainWindow", "Home"))
        self.language_label.setText(_translate("MainWindow", "Language"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.login_tab), _translate("MainWindow", "Login"))
        self.label_23.setText(_translate("MainWindow", "Wallet Summary"))
        self.label_25.setText(_translate("MainWindow", "0"))
        self.label_15.setText(_translate("MainWindow", "Total Normal"))
        self.label_20.setText(_translate("MainWindow", "Total Activated"))
        self.label_22.setText(_translate("MainWindow", "0"))
        self.pushButton.setText(_translate("MainWindow", "Refresh"))
        self.label_2.setText(_translate("MainWindow", "Last Update:  00:00"))
        self.label_12.setText(_translate("MainWindow", "CPU"))
        self.label_4.setText(_translate("MainWindow", "Mining"))
        self.label_16.setText(_translate("MainWindow", "Unknow"))
        self.label_24.setText(_translate("MainWindow", "Staking"))
        self.label_18.setText(_translate("MainWindow", "0"))
        self.label_17.setText(_translate("MainWindow", "Mining Status"))
        self.label_21.setText(_translate("MainWindow", "Copy Pubkey"))
        self.label_19.setText(_translate("MainWindow", "Copy Address"))
        self.label_3.setText(_translate("MainWindow", "Chain Sync"))
        self.label_9.setText(_translate("MainWindow", "Current Block"))
        self.label_6.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "Diffculty"))
        self.label_8.setText(_translate("MainWindow", "0"))
        self.label_11.setText(_translate("MainWindow", "Longest Chain"))
        self.label_28.setText(_translate("MainWindow", "0"))
        self.label_27.setText(_translate("MainWindow", "Connections"))
        self.label_5.setText(_translate("MainWindow", "Chain Status"))
        self.mcl_tab.setTabText(self.mcl_tab.indexOf(self.chain_tab), _translate("MainWindow", "Chain"))
        self.mcl_tab.setTabText(self.mcl_tab.indexOf(self.wallet_tab), _translate("MainWindow", "Wallet"))
        self.mcl_tab.setTabText(self.mcl_tab.indexOf(self.credit_tab), _translate("MainWindow", "Credit Transaction"))
        self.mcl_tab.setTabText(self.mcl_tab.indexOf(self.person_tab), _translate("MainWindow", "Persons"))
        self.mcl_tab.setTabText(self.mcl_tab.indexOf(self.settings_tab), _translate("MainWindow", "Setting"))
        self.mcl_tab.setTabText(self.mcl_tab.indexOf(self.exit_tab), _translate("MainWindow", "Exit"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.marmara_tab), _translate("MainWindow", "Marmara"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.install_tab), _translate("MainWindow", "Install"))

